django/Courses/Courses/urls.py
from django.urls import path,include

urlpatterns = [
    path('', include('courses_app.urls')),
]

django/Courses/courses_app/urls.py
from django.urls import path     
from . import views

app_name = 'courses_app'
urlpatterns = [

    path('', views.index, name='home_page'),                                       
    path('add_course', views.add_course, name='add_course'),                                       
    path('comment_page/<int:id>', views.comment_page, name='comment_page'),                                       
    path('delete_course/<int:id>', views.delete_course, name='delete_course'),                                       

]

django/Courses/courses_app/models.py
from django.db import models

# Create your models here.
class Validate(models.Manager):
    def error_check(self, data):
        errors = {}

        # Validate : name is at least 5 characters
        if len(data['name']) < 5:
            errors['name'] = 'The <strong> Name </strong> Should be at least <strong> 5 </strong> characters'

        # Validate : Description must be at least 15 character
        print(f"Data desc len : {len(data['desc'])}")
        if len(data['desc']) < 15:
            errors['desc'] = "The <strong> Description </strong> must be at least <strong> 15 </strong> characters"

        return errors

class Courses(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = Validate()


class Comments(models.Model):
    course = models.ForeignKey(Courses,related_name= 'comments', on_delete=models.CASCADE)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

django/Courses/courses_app/views.py
from django.shortcuts import render, redirect
from courses_app.models import Courses,Comments
from django.contrib import messages
def index(request):
    context = {
        'courses' : Courses.objects.all()
    }
    return render(request, 'index.html', context)

def add_course(request):
    # Validate The Posted Data from the form
    error = Courses.objects.error_check(request.POST)
    # Check if there exists any error massage
    if len(error) > 0:
        for key, value in error.items():
            messages.error(request,value)
        return redirect('/')
    # Create the object if no errors exists
    else:
        new_course = Courses.objects.create(name = request.POST['name'], desc = request.POST['desc'])
        return redirect('/')

def comment_page(request,id):
    return redirect('/')

def delete_course(request,id):
    course_delete = Courses.objects.get(id=id)
    course_delete.delete()
    return redirect('/')

django/Courses/courses_app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>index page</title>
    {% load static %}
    <!-- {% csrf_token %} -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</head>

<body style="background-color: rgba(231, 233, 249, 0.707);">





    <div class="container border mt-6" style="background-color: white;">
        <!-- Application Form Section -->
        <form class=" mt-4" action="{% url 'courses_app:add_course'%}" method="post">
            {% csrf_token %}
            <h3>Add a new Course</h3>
            <!-- The Validation Error Massages Section -->
            {% if messages %}
            <div class="row justify-content-center">
                <div class="col-sm-6">
                    {% for massage in messages%}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>Warring ! :</strong> {{massage|safe}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
            <!-- Name Input Section -->
            <div class="row form-group justify-content-left  mt-3">
                <div class="col-sm-1 ">
                    <label class="col-form-label">Name:</label>
                </div>
                <div class="col-sm-4">
                    <input class="form-control" type="text" name="name" placeholder="Enter the Course Name">
                </div>
                <!-- Description Input Section -->
                <div class="row form-group justify-content-left  mt-3  ">
                    <div class="col-sm-1 ">
                        <label class="col-form-label ">Description:</label>
                    </div>

                    <div class="col-sm-4">
                        <textarea name="desc" placeholder="Enter the Description" class="form-control" name="" id=""
                            rows="10" style="resize: none;"></textarea>
                    </div>
                </div>
                <div class="row justify-content-left mt-3">
                    <div class="col-sm-5 ">
                        <div class="row justify-content-end">
                            <button type="submit" class="btn btn-primary btn-lg border col-sm-2">Add</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <h3 class="mb-5 mt-3">Courses</h3>
        <!-- Table Section To Display the Courses Data -->
        <table class=" table table-striped table-hover table-bordered text-center ">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Course Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Data Add</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for course in courses %}

                <tr>
                    <!-- Iterate throughout the data coming from courses -->
                    <th scope="row">{{course.id}}</th>
                    <td>{{course.name}}</td>
                    <td>{{course.desc}}</td>
                    <td>{{course.created_at}}</td>
                    <td>
                        <a href="{% url 'courses_app:comment_page' id=course.id %}">Comment</a> | |
                        <a href="#" data-toggle="modal"
                            data-target="#a{{course.id}}">Delete</a>
                    </td>
                </tr>
                <!-- Create a Model that contain The current course data -->
                <div class="modal fade show mt-6" id="a{{course.id}}" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Delete Confirming</h5>
                            </div>
                            <div class="modal-body">
                                <p>Are you Sure you Want ot Delete This Courses <strong> {{course.name}} </strong> ?</p>
                                <div class="row">
                                    <div class="col-sm-4">
                                        Name :
                                    </div>
                                    <div class="col-sm-8">
                                    <strong> {{course.name}}</strong>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-4">
                                        Description :
                                    </div>
                                    <div class="col-sm-8">
                                        <strong>{{course.desc}}</strong>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <a href="{% url 'courses_app:delete_course' id=course.id %}" class="btn btn-danger">Delete</a>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                
                {% endfor %}
            </tbody>
        </table>
        

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script></body>
    

</body>


</html>