django/Temp_files/urls.py
from django.urls import path     
from . import views

app_name = 'TV_Show_app'
urlpatterns = [
    path('show', views.index, name='show_page'),                                   # Add a New Book Page
    path('', views.index, name='root_page'),                                        # Add a New Book Page
    path('show/new', views.new_show, name='show_new'),                              # Add a New Book Page
    path('show/new/create', views.create_new_show, name='create_show_new'),                              # Add a New Book Page
    path('show/<int:id>', views.show_details, name='show_details'),                              # Add a New Book Page
    path('show/<int:id>/edit', views.show_edit, name='show_edit'),                              # Add a New Book Page
    path('show/<int:id>/update', views.show_update, name='show_update'),                              # Add a New Book Page
    path('show/<int:id>/delete', views.show_delete, name='show_delete'),                              # Add a New Book Page
]

django/Temp_files/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>index page</title>
    {% load static %}
    <!-- {% csrf_token %} -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>

<body style="background-color: rgba(231, 233, 249, 0.707);">
    <div class="container border mt-6" style="background-color: white;">
        <h1 class="mb-5 mt-3">Shows</h1>
        <!-- Table Section To Display the Shows Data -->
        <table class=" table table-striped table-hover table-bordered text-center ">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Network</th>
                    <th scope="col">Release Date</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for show in shows %}
                <tr><!--  Iterate throughout the data coming from shows -->
                    <th scope="row">{{show.id}}</th>
                    <td>{{show.title}}</td>
                    <td>{{show.network}}</td>
                    <td>{{show.release_date}}</td>
                    <td>
                        <a href="{% url 'TV_Show_app:show_details' id=show.id %}">Show</a> |
                        <a href="{% url 'TV_Show_app:show_edit' id=show.id %}">Edit</a> |
                        <a href="{% url 'TV_Show_app:show_delete' id=show.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'TV_Show_app:show_new'%}" class="btn btn-primary mb-3">Add a New Show</a>
<!-- 
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Holy guacamole!</strong> You should check in on some of those fields below.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Holy guacamole!</strong> You should check in on some of those fields below.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Holy guacamole!</strong> You should check in on some of those fields below.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div> -->

</body>
{% load static %}
<script src="{% static 'Js/bootstrap.bundle.js' %}"></script>

</html>