django/Favorite_Books/Favorite_Books/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('fav_books_app.urls')),
]

django/Favorite_Books/fav_books_app/urls.py
from django.urls import path     
from . import views

app_name = 'fav_books_app'
urlpatterns = [

    path('', views.index),                                       
    path('success', views.success , name='success'),                                       
    path('success_redirect', views.success_redirect , name='success_redirect'),                                       
    path('reg_process', views.reg_process, name='reg_process'),                                       
    path('login_process', views.login, name='login_process'),                                       
    path('logout_process', views.logout, name='logout_process'),                                       
    path('msg_process', views.msg_process, name='msg_process'),                                       
    path('comment_process', views.comment_process, name='comment_process'),   

    path('books', views.books_page, name='books'),                                    
    path('book_process_add', views.book_process_add, name='book_process_add'),                                    
    path('book_details/<int:id>', views.book_details, name='book_details'),                                
    path('book_process_edit/<int:id>', views.book_process_edit, name='book_process_edit'),                                
    path('add_to_fav/<int:user_id>/<int:book_id>/', views.add_to_fav, name='add_to_fav'),                                
    path('unfav/<int:user_id>/<int:book_id>/', views.unfav, name='unfav'),                                
    path('delete_book/<int:book_id>/', views.delete_book, name='delete_book'),                                


]

django/Favorite_Books/fav_books_app/models.py
from django.db import models
import re


# Create your models here.
class Validation(models.Manager):
    def validate(self, data):
        error = {}

        if len(data['first_name']) < 2 :
            error['firs_name'] = "First Name should be at least 2 characters"
        
        if len(data['last_name']) < 2:
            error['last_name'] = "Last Name should be at least 2 characters"
        
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if not EMAIL_REGEX.match(data['email']):    # test whether a field matches the pattern            
            error['email'] = "Invalid email address!"
        
        if data['password'] != data['conf_password']:
            error['password_conf'] = "Password and Password Confirmation should Match!"
        
        if len(data['password']) < 8 :
            error['password'] = "Password Must be at least 8 characters"
        return error

class Users(models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    email=models.CharField(max_length=100)
    password=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    objects = Validation()
    # messages : a list of Massage instance
    # comments : a list of Comment instance
    # fav_books: a list of fav books (liked) by this user


class Message(models.Model):
    message = models.TextField()
    user = models.ForeignKey(Users,related_name="messages",on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    # comments : a list of Comment instance


class Comment(models.Model):
    comment = models.TextField()
    massage = models.ForeignKey(Message, related_name="comments", on_delete=models.CASCADE)
    user = models.ForeignKey(Users, related_name="comments", on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)


class BookValidation(models.Manager):
    def book_validation(self,data):
        errors = {}
        if len(data['title']) < 1:
            errors['title'] = "You Must Add a Title! "
        
        if len(data['desc']) < 5:
            errors['desc'] = "The Book Description must be at least 5 characters!"
        
        return errors


class Book(models.Model):
    title = models.CharField(max_length=255)
    liked_by = models.ManyToManyField(Users, related_name="fav_books")
    uploaded_by = models.ForeignKey(Users, related_name= "books_uploaded", on_delete=models.CASCADE)
    desc = models.TextField(default="NO Description Available")
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    objects = BookValidation()

django/Favorite_Books/fav_books_app/views.py
from django.shortcuts import render, redirect
from fav_books_app.models import *
from django.contrib import messages
import bcrypt

# Create your views here.


def index(request):
    return render(request, 'index.html')


def login(request):
    # see if the username provided exists in the database
    user = Users.objects.filter(email=request.POST['email'])
    if user:
        logged_user = user[0]
        if bcrypt.checkpw(request.POST['password'].encode(), logged_user.password.encode()):
            # if we get True after checking the password, we may put the user id in session
            request.session['user_id'] = logged_user.id
            messages.success(request, "You have Successfully logged in")
            return redirect('/success')
        else:
            # if we didn't find anything in the database by searching by username or if the passwords don't match,
            messages.error(request, "Email or Password incorrect")
            return redirect('/')
    else:
        # if we didn't find anything in the database by searching by username or if the passwords don't match,
        messages.error(request, "Email or Password incorrect")
        return redirect('/')

# : This will clear the massages from messages (error / success) --> redirect to /success
def success_redirect(request):
    list(messages.get_messages(request))
    return redirect('/success')

# : The main page after the user successfully logged in, it will open "The Wall"

def success(request):
    user = Users.objects.get(id=request.session['user_id'])
    msg_objects = Message.objects.all().order_by("-created_at")
    comment_objects = Comment.objects.all().order_by("-created_at")
    context = {
        'first_name': user.first_name,
        'last_name': user.last_name,
        'msg_objects': msg_objects,
        'comment_objects': comment_objects,

    }
    return render(request, 'success.html', context)


def reg_process(request):
    # Validation Part Is here
    error = Users.objects.validate(request.POST)
    if len(error) > 0:
        for key, value in error.items():
            messages.error(request, value)
        return redirect('/')
    else:  # if Validation passed store the user in the db and encrypt the password
        password = request.POST['password']
        ps_hash = bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()
        Users.objects.create(
            first_name=request.POST['first_name'], last_name=request.POST[
                'last_name'], email=request.POST['email'], password=ps_hash
        )
        messages.success(request, "User has been created Successfully!")
        return redirect('/')

# Logout : will terminate the sessions and redirect to the root.


def logout(request):
    # This will clear the massages from messages (error / success)
    list(messages.get_messages(request))
    request.session.flush()
    return redirect('/')

#  Message Processing: Process the comment : It will take the message and store it in the (message) table at db -- > redirect to /success


def msg_process(request):
    msg = request.POST['msg']
    user = Users.objects.get(id=request.session['user_id'])
    # Validation part for the massages will be added here at the future
    Message.objects.create(message=msg, user=user)
    # to remove the massages.error/success
    list(messages.get_messages(request))
    return redirect('/success')

# Comment Processing: Process the comment : It will take the comment and store it in the (Comment) table at db -- > redirect to /success


def comment_process(request):
    comment = request.POST['comment']
    user = Users.objects.get(id=request.session['user_id'])
    massage = Message.objects.get(id=request.POST['msg_id'])
    # Validation part for the comments will be added here at the future
    # to remove the massages.error/success
    list(messages.get_messages(request))
    # Created a new comment in the db
    Comment.objects.create(comment=comment, user=user, massage=massage)
    return redirect('/success')

# Webpage->|Books| : Open Books
def books_page(request):
    user = Users.objects.get(id=request.session['user_id'])
    books = Book.objects.all()
    tag = check_fav_users(user.id, books)
    context = {
        'first_name': user.first_name,
        'last_name': user.last_name,
        'user': user,
        'books': books,
        'tag': tag
    }
    return render(request, 'books.html', context)

# Add New Book : This will add new book to the db (Validation included)


def book_process_add(request):
    title = request.POST['title']
    desc = request.POST['desc']
    user_id = request.session['user_id']
    # Validation part
    errors = Book.objects.book_validation(request.POST)

    if len(errors) > 0:
        for key, value in errors.items():
            messages.error(request, value)

    else:
        Book.objects.create(title=title, desc=desc,
                            uploaded_by=Users.objects.get(id=user_id))

    return redirect('/books')

# Webpage -> |Book Details| : Open selected book page and present the book details
# : If the user is the owner of the book they can edit it


def book_details(request, id):
    user = Users.objects.get(id=request.session['user_id'])
    book = Book.objects.get(id=id)
    context = {
        'book': book,
        'user': user,
    }
    return render(request, 'book_details.html', context)

# Process -> : Edit the details of the selected book by the created user.

def book_process_edit(request, id):
    book_id = id
    # Validation Part
    errors = Book.objects.book_validation(request.POST)
    if len(errors) > 0:
        for key, value in errors.items():
            messages.error(request, value)
    else:
        book_title = request.POST['title']
        book_desc = request.POST['desc']
        book = Book.objects.get(id=book_id)
        book.title = book_title
        book.desc = book_desc
        book.save()
        messages.success(request, "Book Has been successfully edited")
    return redirect('/book_details/' + str(book_id))

# Process -> Add Book to Fav List : Add the selected book to the user in session to his/her favorite books.
def add_to_fav(request, user_id, book_id):
    user = Users.objects.get(id=user_id)
    book = Book.objects.get(id=book_id)

    book.liked_by.add(user)
    return redirect('/books')

''' Process -> Purpose: return a dictionary contains all fav status of the books (if the user have the book at their fav list or not)
# : The dictionary structured as following:
# : dictionary = {
    'book id' : 'favorite status'
    }

    book id : is a variable Key, which represent the related book fav status to session user. 
    favorite status : is the favorite status related to the session user

An example :
    dic = {
    '1' : 'f"<a href='/add_to_fav/{user_id}/{book.id}'> Add to Favorite </a>"' // The user do not have this book as fav in their list
    '2' : '"<p> You already liked this book!<p>"'                              // The user have this book as fav in their list
    '3' : '"<p> You already liked this book!<p>"'                              // The user have this book as fav in their list
    
    }
    '''
def check_fav_users(user_id, books):
    dic = {}

    for book in books:

        # if the query set is empty then 'Add to Favorite'
        if not book.liked_by.all().exists(): 
            dic[f'{book.id}'] = f"<a href='/add_to_fav/{user_id}/{book.id}'> Add to Favorite </a>"
            continue
        for user in book.liked_by.all():
            # If the user already liked this book then 'You Already Liked this Book !' and break the loop
            if (user.id == user_id):
                dic[f'{book.id}'] = "<p> You already liked this book!<p>"
                break 
            # if the program reached this level then this mean user didn't have the book at their favorite list then 'Add to Favorite'
            dic[f'{book.id}'] = f"<a href='/add_to_fav/{user_id}/{book.id}'> Add to Favorite </a>" 

    return dic

# Process -> Remove Book From Fav List: Add the selected book to the user in session to his/her favorite books.
def unfav(request, book_id, user_id):
    book = Book.objects.get(id=book_id)
    user = Users.objects.get(id=user_id)
    book.liked_by.remove(user)
    return redirect(f'/book_details/{book_id}')

# Process -> Delete Book: Add the selected book to the user in session to his/her favorite books.
def delete_book(request, book_id):
    book = Book.objects.get(id=book_id)
    book.delete()
    return redirect('/books')

django/Favorite_Books/fav_books_app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>index page</title>
    {% load static %}
    <!-- {% csrf_token %} -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body style="background-color: rgba(231, 233, 249, 0.707);">
    <!-- The Validation Error Massages Section -->
    <div class="container mt-6 mb-3" style="background-color: white;">
        {% if messages %}
        <div class="row justify-content-center mt-3">
            <div class="col-sm-12">
                {% for massage in messages %}
                {% if massage.tags == 'error' %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Warring ! :</strong> {{massage}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% if massage.tags == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Success ! :</strong> {{massage}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endif %}
        <div class="row">
            <div class="col-sm-6 ">

                <h2 class="mt-3 mb-5">Registration</h2>
                <form action="{% url 'fav_books_app:reg_process' %}" method="post">
                    {% csrf_token %}
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">First Name:</label>
                        </div>
                        <div class="col-sm-6">
                            <input type="text" name="first_name" class="form-control">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">Last Name:</label>
                        </div>
                        <div class="col-sm-6">
                            <input type="text" name="last_name" class="form-control">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">Email:</label>
                        </div>
                        <div class="col-sm-6">
                            <input type="email" name="email" class="form-control">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">Password:</label>
                        </div>
                        <div class="col-sm-6">
                            <input type="password" name="password" class="form-control">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">Confirm PW:</label>
                        </div>
                        <div class="col-sm-6">
                            <input type="password" name="conf_password" class="form-control">
                        </div>
                    </div>
                    <div class="row mb-3 justify-content-center">
                        <div class="col-sm-6">
                            <button type="submit" class="btn btn-primary">Register</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-sm-6">
                <h2 class="mt-3 mb-5">Login</h2>
                <form action="{% url 'fav_books_app:login_process' %}" method="post">
                    {% csrf_token %}
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label for="" class="col-form-label">Email</label>
                        </div>
                        <div class="col-sm-6">
                            <input type="email" name="email" class="form-control">
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label for="" class="col-form-label">Password</label>
                        </div>
                        <div class="col-sm-6">
                            <input type="password" name="password" class="form-control">
                        </div>
                    </div>
                    <div class="row mb-3 justify-content-center">
                        <div class="col-sm-6">
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </div>
                </form>
            </div>

        </div>

    </div>
    </div>



    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script></body> -->


</body>


</html>

django/Favorite_Books/fav_books_app/templates/success.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>index page</title>
    {% load static %}
    <!-- {% csrf_token %} -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body style="background-color: rgba(231, 233, 249, 0.707);">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">Test APP</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'fav_books_app:success_redirect' %}">Wall</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'fav_books_app:books' %}">Books</a>
                    </li>
                </ul>
                <form class="d-flex align-items-center">
                    <h4> Welcome , {{first_name}} {{last_name}}</h4>
                    <a href="{% url 'fav_books_app:logout_process' %}" class="ms-3 btn btn-secondary">Logout</a>
                </form>
            </div>
        </div>
    </nav>

    <div class="container mt-6 pt-4" style="background-color: white;">

        <div class="row justify-content-end mb-3">
            <div class="col-sm-10">
                <h1 class="aligne-item-center">Welcome, {{first_name}} {{last_name}}</h1>
            </div>
        </div>
        <!-- The Validation Error Massages Section -->
        {% if messages %}
        <div class="row justify-content-center">
            <div class="col-sm-6">
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Login:</strong> You Have Successfully logged in <strong> {{first_name}}
                        {{last_name}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        </div>
        {% endif %}

        <main class="pb-5">
            <form action="{% url 'fav_books_app:msg_process' %}" method="post">
                {% csrf_token %}
                <div class="row justify-content-center">
                    <div class="col-sm-10">
                        <label for="exampleFormControlTextarea1" class="form-label"><strong>Write a
                                Massage</strong></label>
                        <textarea name="msg" class="form-control" id="exampleFormControlTextarea1" rows="5"></textarea>
                    </div>
                    <div class="row justify-content-end mt-3 ">
                        <div class="col-sm-3  text-center me-3">
                            <button type="submit" class="btn btn-primary">Post a massage</button>
                        </div>
                    </div>

                </div>


            </form>
            {% for msg in msg_objects %}
            <div class="row justify-content-center mt-5 mb-1">
                <div class="col-sm-10">
                    <label class="form-label"> from : {{msg.user.first_name}} {{msg.user.last_name}} Created :
                        {{msg.created_at}}</label>
                    <div class="card">
                        <div class="card-body">
                            {{msg.message}}
                        </div>
                    </div>
                </div>
            </div>
            {% for comment in comment_objects %}
            {% if comment.massage.id == msg.id%}
            <div class="row justify-content-center">
            <div class="col-sm-10 ms-5"> <strong>{{comment.user.first_name}} {{comment.user.last_name}} </strong> {{comment.created_at}}</div>
                <div class="col-sm-10 ms-5">{{comment.comment}} </div>
                <div class="col-sm-8">
                    <hr class="hr">
                </div>
                
            </div>
            {% endif %}
            {% endfor %}
            <form action="{% url 'fav_books_app:comment_process' %}" method="post">
                {% csrf_token %}
                <div class="  row justify-content-center">
                    <div class="col-sm-10">
                        <div class="  row justify-content-end">
                            <div class="col-sm-10">
                                <label for="exampleFormControlTextarea1" class="form-label"><strong>Write a
                                        Comment</strong></label>
                                <textarea name="comment" class="form-control" id="exampleFormControlTextarea1"
                                    rows="2"></textarea>
                                    <input type="hidden" name="msg_id" value= {{msg.id}}>
                            </div>
                        </div>

                    </div>
                    <div class="row justify-content-end mt-3 ">
                        <div class="col-sm-3  text-center me-3">
                            <button type="submit" class="btn btn-primary">Post a comment</button>
                        </div>
                    </div>
            </form>
            {% endfor %}
        </main>
    </div>


    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script></body> -->


</body>


</html>