django/python_examp/app/urls.py
from django.urls import path     
from . import views

app_name = 'app'
urlpatterns = [
    # Page Section:
    path('', views.index),
    path('home',views.success, name = 'home'),
    path('table',views.table, name = 'table'),
    path('form',views.form, name = 'form'),
    path('team/new',views.new_team, name = 'new_team'),
    path('team/<int:id>',views.team_details, name = 'team_details'),
    path('team/<int:team_id>/edit',views.team_edit, name = 'team_edit'),

    # Process Section
    path('reg_process', views.reg_process, name='reg_process'),   # Registration Process                                    
    path('login_process', views.login_process, name='login_process'),   # Login Process                                    
    path('success_redirect_process', views.success_redirect_process, name='success_redirect_process'),   # Login Process                                    
    path('logout_process', views.logout_process, name='logout_process'),   # Login Process                                    
    path('create_new_team_process', views.create_new_team_process, name='create_new_team_process'),   # Create New Team Process                                    
    path('new_team_redirect_process', views.new_team_redirect_process, name='new_team_redirect_process'),   # Login Process                                    
    path('edit_new_team_process/<int:team_id>', views.edit_new_team_process, name='edit_new_team_process'),   # Login Process  
    path('delete_team/<int:team_id>/', views.delete_team, name='delete_team'),                                   
    path('add_player/<int:team_id>/', views.add_player_process, name='add_player_process'),                                   

]

django/python_examp/python_examp/urls.py
from django.urls import path,include

urlpatterns = [
    path('', include('app.urls')),
    
]

django/python_examp/app/templates/form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>index page</title>
    {% load static %}
    <!-- {% csrf_token %} -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body style="background-color: rgba(231, 233, 249, 0.707);">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">Test APP</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Link 1</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Link 2</a>
                    </li>
                </ul>
                <form class="d-flex align-items-center">
                    <h4> Welcome , {{user_object.first_name}} {{user_object.last_name}}</h4>
                    <!-- Logout -->
                    <a href="{% url 'app:logout_process' %}" class="ms-3 btn btn-secondary">Logout</a>
                </form>
            </div>
        </div>
    </nav>

    <div class="container mt-6 pt-4" style="background-color: white;">


        <main class="pb-5">
            <div class="row justify-content-center ">
                <!-- Left Section : Table -->
                <main class="col-sm-12 text-center">
                    <form action="{% url 'app:login_process' %}" method="post">
                        {% csrf_token %}
                        <!-- Email  -->
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label for="" class="col-form-label">Email</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="email" name="email" class="form-control">
                            </div>
                        </div>
                        <!-- PassWord -->
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label for="" class="col-form-label">Password</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="password" name="password" class="form-control">
                            </div>
                        </div>
                        <!-- Description Area -->
                        <div class="row mb-3 ">
                            <div class="col-sm-3  ">
                                <h5 class="fw-bold">Description:</h5>
                                <!-- This Can be replaced with a Label from above instead of h5-->
                            </div>
                            <div class="col-sm-6">
                                <textarea name="desc" class="form-control" rows="5">Description part</textarea>
                            </div>
                        </div>
                        <!-- Dropdown list -->
                        <div class="row mb-3 ">
                            <div class="col-sm-3  "> Please Select from the menu :</div>
                            <div class="col-sm-6">
                                <select class="form-select" aria-label="Default select example">
                                    <option selected>Open this select menu</option>
                                    <option value="1">One</option>
                                    <option value="2">Two</option>
                                    <option value="3">Three</option>
                                </select>
                            </div>
                        </div>
                        <!-- Radio button -->
                        <div class="row mb-3 ">
                            <div class="col-sm-3  ">
                                <label class="form-check-label" for="flexRadioDefault1">
                                    Default radio
                                </label>
                            </div>
                            <div class="col-sm-6 d-flex">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="same_name" value="1">
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="same_name" value="2">
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="same_name" value="3">
                                </div>
                            </div>
                        </div>
                        <!-- Check Boxes -->
                        <!-- Check Box : 1 -->
                        <div class="row mb-3 ">
                            <div class="col-sm-3  ">
                                <label class="form-check-label" for="flexCheckDefault">
                                    Default checkbox
                                </label>
                            </div>
                            <div class="col-sm-6 d-flex justify-content-start">
                                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                            </div>
                        </div>
                        <!-- Check Box : 2 -->
                        <div class="row mb-3 ">
                            <div class="col-sm-3  ">
                                <label class="form-check-label" for="flexCheckDefault">
                                    Second Default checkbox
                                </label>
                            </div>
                            <div class="col-sm-6 d-flex justify-content-start">
                                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                            </div>
                            <!-- Login Button -->
                            <div class="row mb-3 justify-content-center">
                                <div class="col-sm-6 ">
                                    <button type="submit" class="btn btn-primary">Post</button>
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </div>
                                
                            </div>
                    </form>
                </main>
            </div>
        </main>
    </div>


    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script></body> -->


</body>


</html>

django/python_examp/app/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>home page</title>
    {% load static %}
    <!-- {% csrf_token %} -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body style="background-color: rgba(231, 233, 249, 0.707);">
    <!-- Navigation Bar -->
    {% if user_session %} 
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <h4> Welcome , {{user_object.user_name}}</h4>
                    </li>
                    <li class="nav-item">
                        <form class="d-flex align-items-center">

                            <!-- Logout -->
                            <a href="{% url 'app:logout_process' %}" class="ms-3 btn btn-secondary">Logout</a>
                        </form>
                    </li>
                </ul>

            </div>
        </div>
    </nav>

    <div class="container mt-6 pt-4" style="background-color: white;">

        <!-- The Validation Error Massages Section -->
        {% if messages %}
        <div class="row justify-content-center">
            <div class="col-sm-6">
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Login:</strong> You Have Successfully logged in <strong> {{user_object.user_name}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        </div>
        {% endif %}

        <main class="pb-5">
            <!-- Dash Board Table -->
            <div class="row justify-content-center border">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Team Name</th>
                            <th scope="col">Skill Level (1-5) </th>
                            <th scope="col">players</th>
                            <th scope="col">Game Day</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for team in team_object%}
                        <tr>
                            <td><a href="{% url 'app:team_details' id=team.id %}">{{team.team_name}}</a> </td>
                            <td>{{team.skill_level}}</td>
                            <td>{{team.players.all.count}} / 9</td>
                            <td>{{team.game_day}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a href="{% url 'app:new_team_redirect_process' %}" class="btn btn-primary btn-lg">Create a New Team</a>
            </div>
            <hr>

            
        </main>
    </div>
    {% else %}
    <h1> YOU NEED To BE LOGGED IN</h1>
    {% endif %}


    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script></body> -->


</body>


</html>

django/python_examp/app/templates/team_details.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>index page</title>
    {% load static %}
    <!-- {% csrf_token %} -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body style="background-color: rgba(231, 233, 249, 0.707);">
    <!-- The Validation Error Massages Section -->
    <div class="container mt-6 mb-3" style="background-color: white;">
        {% if user_session %} 
        
        {% if messages %}
        <div class="row justify-content-center mt-3">
            <div class="col-sm-12">
                {% for massage in messages %}
                {% if massage.tags == 'error' %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Warring ! :</strong> {{massage}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% if massage.tags == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Success ! :</strong> {{massage}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endif %}


        <div class="row">
            <!-- Left Section -->
            <div class="col-sm-12  mt-3 mb-2 ">
                <h2>{{team_object.team_name}} Details:</h2>
            </div>
            <div class="row mb-2">
                <div class="col-sm-12">
                    <a href="{% url 'app:success_redirect_process' %}"> Dashboard </a>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-sm-6 ">
                    <!-- Details Section -->
                    {% csrf_token %}
                    <!-- Team Name -->
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">Team Name:</label>
                        </div>
                        <div class="col-sm-6">
                            <label class="col-form-label" for=""><strong>{{team_object.team_name}}</strong></label>
                        </div>
                    </div>
                    <!-- Skill Level -->
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">Skill Level (1-5):</label>
                        </div>
                        <div class="col-sm-6">
                            <label class="col-form-label" for=""><strong>{{team_object.skill_level}}</strong></label>
                        </div>
                    </div>
                    <!-- Game DAy -->
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">Game Day:</label>
                        </div>
                        <div class="col-sm-6">
                            <label class="col-form-label" for=""><strong>{{team_object.game_day}}</strong></label>
                        </div>

                        <!-- Players -->
                        <div class="row mb-3">
                            {% if team_object.players.all.count >= 9 %}
                            <div class="col-sm-12">
                                <h3>Team Is Full !</h3>
                            </div>
                            {% endif %}
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Players</label>

                                <ul>
                                    {% for player in player_object%}
                                    <li>{{player.player_name}}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                            
                            

                        </div>

                    </div>
                </div>
            </div>
            <hr>
            <form action="{% url 'app:add_player_process' team_id=team_object.id %}" method="post">
                {% csrf_token %}
                <div class="row justify-content-center">
                    <div class="col-sm-12">
                        <h3 class="text-center"> Add Player</h3>
                    </div>
                    <div class="row mb-3">
                        <div class="col-sm-3">
                            <label class="col-form-label" for="">Player Name:</label>
                        </div>
                        <div class="col-sm-6">
                            <input type="text" name="player_name" class="form-control">
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-sm-12 text-center">
                            <button type="submit" class="btn btn-primary"> Add Player</button>
                        </div>
                    </div>
            </form>





            {% if current_user.id == team_object.user.id %}
            <div class="row justify-content-start">

                <div class="col-sm-1 me-3">
                    <a class="btn btn-secondary" href="{% url 'app:team_edit' team_id=team_object.id%}">edit</a>
                </div>

                <div class="col-sm-1">
                    <a class="btn btn-danger" href="{% url 'app:delete_team' team_id=team_object.id %}">Delete</a>
                </div>
            </div>
            {% endif %}


        </div>
        {% else %}
        <h1> YOU NEED To BE LOGGED IN</h1>
        {% endif %}
    </div>



    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script></body> -->


</body>


</html>

django/python_examp/app/templates/team_edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>index page</title>
    {% load static %}
    <!-- {% csrf_token %} -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</head>

<body style="background-color: rgba(231, 233, 249, 0.707);">
    <!-- The Validation Error Massages Section -->
    <div class="container mt-6 mb-3" style="background-color: white;">
        {% if messages %}
        <div class="row justify-content-center mt-3">
            <div class="col-sm-12">
                {% for massage in messages %}
                {% if massage.tags == 'error' %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Warring ! :</strong> {{massage}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% if massage.tags == 'success' %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Success ! :</strong> {{massage}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endif %}

        {% if current_user.id == team_object.user.id %}
        <div class="row"> 
            <!-- Left Section -->
            <div class="col-sm-12  mt-3 mb-2 ">
                <h2>Edit {{team_object.team_name}}</h2>
            </div>
            <div class="row mb-2">
                <div class="col-sm-12">
                    <a href="{% url 'app:success_redirect_process' %}"> Dashboard </a>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-sm-6 ">
                    <!-- Registration Section -->
                    <form action="{% url 'app:edit_new_team_process' team_id=team_object.id %}" method="post">
                        {% csrf_token %}
                        <!-- Team Name -->
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Team Name:</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="text" name="team_name" class="form-control" value="{{team_object.team_name}}">
                            </div>
                        </div>
                        <!-- Skill Level -->
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Skill Level (1-5):</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="number" name="skill_level" class="form-control" value="{{team_object.skill_level}}">
                            </div>
                        </div>
                        <!-- Game DAy -->
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Game Day:</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="text" name="game_day" class="form-control" value="{{team_object.game_day}}">
                            </div>
                            
                        </div>
                        
                        <!-- Submit Button -->
                        <div class="row mb-3 justify-content-center">
                            <div class="col-sm-6 d-flex justify-content-around">
                                <a href="{% url 'app:delete_team' team_id=team_object.id %}" class="btn btn-danger">Delete</a>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {% else %}
        <div class="row"> 
            <!-- Left Section -->
            <div class="col-sm-12  mt-3 mb-2 ">
                <h2>{{team_object.team_name}} Details:</h2>
            </div>
            <div class="row mb-2">
                <div class="col-sm-12">
                    <a href="{% url 'app:success_redirect_process' %}"> Dashboard </a>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-sm-6 ">
                    <!-- Details Section -->
                        {% csrf_token %}
                        <!-- Team Name -->
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Team Name:</label>
                            </div>
                            <div class="col-sm-6">
                                <label class="col-form-label" for=""><strong>{{team_object.team_name}}</strong></label>
                            </div>
                        </div>
                        <!-- Skill Level -->
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Skill Level (1-5):</label>
                            </div>
                            <div class="col-sm-6">
                                <label class="col-form-label" for=""><strong>{{team_object.skill_level}}</strong></label>
                            </div>
                        </div>
                        <!-- Game DAy -->
                        <div class="row mb-3">
                            <div class="col-sm-3">
                                <label class="col-form-label" for="">Game Day:</label>
                            </div>
                            <div class="col-sm-6">
                                <label class="col-form-label" for=""><strong>{{team_object.game_day}}</strong></label>
                            </div>
                            
                        </div>

                </div>
            </div>
        </div>
        {% endif %}

    </div>
    </div>



    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script></body> -->


</body>


</html>